apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ticketing-system-booking-scaledobject
spec:
  scaleTargetRef:
    name: ticketing-system-booking
  minReplicaCount: 1
  maxReplicaCount: 20
  triggers:
    - type: redis
      metadata:
        address: ticketing-system-redis:6379
        listName: queue:jobs
        listLength: "10"
