apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-system-booking-status
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketing-system-booking-status
  template:
    metadata:
      labels:
        app: ticketing-system-booking-status
    spec:
      containers:
        - name: booking-status
          image: booking-status:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: ticketing-system-credentials
            - configMapRef:
                name: ticketing-system-config
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
