apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-system-booking
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketing-system-booking
  template:
    metadata:
      labels:
        app: ticketing-system-booking
    spec:
      containers:
        - name: booking
          image: booking:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: ticketing-system-credentials
            - configMapRef:
                name: ticketing-system-config
          startupProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 30
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 20
