apiVersion: v1
kind: Service
metadata:
  name: ticketing-system-frontend
spec:
  type: ClusterIP
  selector:
    app: ticketing-system-frontend
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
