apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ticketing-system.fullname" . }}-credentials
type: Opaque
stringData:
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
  mysql-root-password: {{ .Values.secrets.mysqlRootPassword | quote }}
  mysql-password: {{ .Values.secrets.mysqlPassword | quote }}
  smtp-host: {{ .Values.secrets.smtpHost | quote }}
  smtp-port: {{ .Values.secrets.smtpPort | quote }}
  smtp-user: {{ .Values.secrets.smtpUser | quote }}
  smtp-password: {{ .Values.secrets.smtpPassword | quote }}
  default-admin-email: {{ .Values.secrets.defaultAdminEmail | quote }}
  default-admin-password: {{ .Values.secrets.defaultAdminPassword | quote }}
  razorpay-key-id: {{ .Values.secrets.razorpayKeyId | quote }}
  razorpay-key-secret: {{ .Values.secrets.razorpayKeySecret | quote }}
  razorpay-webhook-secret: {{ .Values.secrets.razorpayWebhookSecret | quote }}
