apiVersion: v1
kind: Service
metadata:
  name: ticketing-system-auth
spec:
  type: ClusterIP
  selector:
    app: ticketing-system-auth
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
