apiVersion: v1
kind: Service
metadata:
  name: ticketing-system-booking-status
spec:
  type: ClusterIP
  selector:
    app: ticketing-system-booking-status
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
