apiVersion: v1
kind: Service
metadata:
  name: ticketing-system-gateway
  namespace: app
spec:
  type: NodePort
  selector:
    app: ticketing-system-gateway
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30081
