apiVersion: v1
kind: Service
metadata:
  name: ticketing-system-notification
spec:
  type: ClusterIP
  selector:
    app: ticketing-system-notification
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
