apiVersion: v1
kind: Service
metadata:
  name: ticketing-system-payment-razorpay
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: ticketing-system-payment-razorpay
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
