apiVersion: v1
kind: Secret
metadata:
  name: ticketing-system-credentials
stringData:
  JWT_SECRET_KEY: "3ae4e366-67ea-4767-bcbb-d40266d7c03d"
  MYSQL_ROOT_PASSWORD: "rootpass"
  MYSQL_PASSWORD: "ticketpass"
  SMTP_HOST: "sandbox.smtp.mailtrap.io"
  SMTP_PORT: "2525"
  SMTP_USER: "ba04ea8026e716"
  SMTP_PASSWORD: "260615d93e79b7"
  DEFAULT_ADMIN_EMAIL: "admin@example.com"
  DEFAULT_ADMIN_PASSWORD: "admin123"
