apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: booking-worker-scaledobject
spec:
  scaleTargetRef:
    name: booking-worker
  minReplicaCount: 1
  maxReplicaCount: 20
  triggers:
    - type: redis
      metadata:
        address: redis:6379
        listName: queue:jobs
        listLength: '10'
